In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
files.upload()

Saving Screen Time Data.csv to Screen Time Data.csv


{'Screen Time Data.csv': b'index,Date,Week Day,Total Screen Time ,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga\n0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0\n1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0\n2,04/19/19,Friday,112,52,40,8,4,0,3,0,0\n3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0\n4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0\n5,04/22/19,Monday,189,68,0,9,3,4,0,0,0\n6,04/23/19,Tuesday,158,56,18,41,12,15,0,0,0\n7,04/24/19,Wednesday,135,98,3,33,16,0,0,0,0\n8,04/25/19,Thursday,52,25,7,3,16,0,0,0,0\n9,04/26/19,Friday,198,76,8,29,15,0,32,0,0\n10,04/27/19,Saturday,116,75,10,20,5,0,0,0,0\n11,04/28/19,Sunday,85,42,22,4,2,0,0,0,0\n12,04/29/19,Monday,109,46,8,13,9,15,1,0,1\n13,04/30/19,Tuesday,79,40,2,9,12,0,0,0,1\n14,05/01/19,Wednesday,127,90,0,10,7,0,0,0,1\n15,05/02/19,Thursday,170,60,3,2,11,0,0,0,1\n16,05/03/19,Friday,91,64,2,18,5,1,1,2,1\n17,05/04/19,Saturday,58,34,4,5,3,0,1,0,1\n18,05/05/19,Sunday,133,109,5,1,3,0,0,0,1\n19,05/06/19,

In [ ]:
df=pd.read_csv('Screen Time Data.csv')

In [ ]:
df.head()

index      Date   Week Day  Total Screen Time   Social Networking  \
0      0  04/17/19  Wednesday                 187                 89   
1      1  04/18/19   Thursday                 123                 78   
2      2  04/19/19     Friday                 112                 52   
3      3  04/20/19   Saturday                 101                 69   
4      4  04/21/19     Sunday                  56                 35   

   Reading and Reference  Other  Productivity  Health and Fitness  \
0                     17     41            22                   0   
1                     17      8             9                   0   
2                     40      8             4                   0   
3                      9     38             2                   0   
4                      2     43             3                   0   

   Entertainment  Creativity  Yoga  
0              0           0     0  
1              0           0     0  
2              3           0     0  
3              3           0     0  
4              1           1     0

In [ ]:
!pip install ydata_profiling

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 390.9/390.9 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 27.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 687.8/687.8 kB 29.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.8/104.8 kB 10.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 82.4 MB/s eta 0:00:00
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=55aa35682ba627800d5f636d70050710199672109e7405aea9b3e48e8adea885
  Stored in directory: /root/.cache/pip/wheels/8d/55/1a/19cd535375ed1ede0c996405ebffe34b196d78e2d9545723a2
Successfully built htmlmin


In [ ]:
from ydata_profiling import ProfileReport
profile=ProfileReport(df,title='Data Profiling Report',explorative=True)

In [ ]:
profile

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
profile.to_file('report.html')

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
files.download('report.html')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Numpy- Numerical Python

Advantages of Numpy Arrays:
1.	Allows several Mathematical Operations
2.	Faster operations


List vs Numpy - Time Taken

In [ ]:
#Time taken by a list
from time import process_time

In [ ]:
my_list=[i for i in range(10000)]
start_time=process_time()
print(start_time)
my_list=[i+5 for i in my_list]
end_time=process_time()
print(end_time)
print(end_time-start_time)

53.126868004
53.127974712
0.0011067079999946827


In [ ]:
import numpy as np
array=np.array([i for i in range(10000)])
start_time=process_time()
print(start_time)
array+=5
end_time=process_time()
print(end_time)
print(end_time-start_time)

53.167532316
53.167785439
0.0002531230000002438


Numpy Arrays

In [ ]:
# creating a 1 dim array
list1=[1,2,3,4]

In [ ]:
list1

[1, 2, 3, 4]

In [ ]:
type(list1)

list

In [ ]:
# convert a list to a numpy array
a=np.array(list1)

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
print(a)

[1 2 3 4]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim

1

In [ ]:
a.shape

(4,)

Initial Placeholders in numpy arrays

In [ ]:
# create a numpy array of Zeros
b=np.zeros((4,5),dtype=int)

In [ ]:
b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
b.shape

(4, 5)

In [ ]:
b.size

20

In [ ]:
# create a numpy array of ones
c=np.ones((4,5))

In [ ]:
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# array of a particular value
d=np.full((5,4),5)

In [ ]:
d

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
# create an identity matrix
e=np.eye(5,dtype=int)

In [ ]:
e

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
# create a numpy array with random values
np.random.seed(42)
f=np.random.random((3,4))

In [ ]:
f

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985]])

In [ ]:
# random integer values array within a specific range
g=np.random.randint(10,100,(3,5))

In [ ]:
g

array([[39, 47, 11, 73, 69],
       [30, 42, 85, 67, 31],
       [98, 58, 68, 51, 69]])

In [ ]:
h=np.random.randn(3,4,10)
"""
The expression h = np.random.randn(3,4,10) generates a 3D NumPy array with a shape of (3,4,10),
where:np.random.randn() generates random values from a standard normal distribution (mean = 0, standard deviation = 1).
The shape (3,4,10) means: 3 slices (or matrices), Each with 4 rows, And 10 columns.
"""

In [ ]:
h

array([[[ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819,
         -0.54438272,  0.11092259, -1.15099358,  0.37569802,
         -0.60063869, -0.29169375],
        [-0.60170661,  1.85227818, -0.01349722, -1.05771093,
          0.82254491, -1.22084365,  0.2088636 , -1.95967012,
         -1.32818605,  0.19686124],
        [ 0.73846658,  0.17136828, -0.11564828, -0.3011037 ,
         -1.47852199, -0.71984421, -0.46063877,  1.05712223,
          0.34361829, -1.76304016],
        [ 0.32408397, -0.38508228, -0.676922  ,  0.61167629,
          1.03099952,  0.93128012, -0.83921752, -0.30921238,
          0.33126343,  0.97554513]],

       [[-0.47917424, -0.18565898, -1.10633497, -1.19620662,
          0.81252582,  1.35624003, -0.07201012,  1.0035329 ,
          0.36163603, -0.64511975],
        [ 0.36139561,  1.53803657, -0.03582604,  1.56464366,
         -2.6197451 ,  0.8219025 ,  0.08704707, -0.29900735,
          0.09176078, -1.98756891],
        [-0.21967189,  0.35711257,  1.47789404, -0

In [ ]:
h.ndim

3

In [ ]:
# array of evenly spaced values --> specifying the number of values required
np.linspace(10,30,7)

array([10.        , 13.33333333, 16.66666667, 20.        , 23.33333333,
       26.66666667, 30.        ])

In [ ]:
# array of evenly spaced values --> specifying the step
print(np.arange(10,30,3))

[10 13 16 19 22 25 28]


In [ ]:
a.dtype

dtype('int64')

Mathematical operations on a np array

In [ ]:
l1=[1,2,3,4]
l2=[5,6,7,8]

In [ ]:
print(l1+l2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
i=np.array(l1)
j=np.array(l2)

In [ ]:
j

array([5, 6, 7, 8])

In [ ]:
i

array([1, 2, 3, 4])

In [ ]:
m=i+j

In [ ]:
m

array([ 6,  8, 10, 12])

In [ ]:
m+2

array([ 8, 10, 12, 14])

In [ ]:
i-j

array([-4, -4, -4, -4])

In [ ]:
i*j

array([ 5, 12, 21, 32])